import type { Locale } from "@/lib/locale";

export interface BimtoolsManualDetailContent {
  notFoundTitle: string;
  metaSuffix: string;
  backToBimtools: string;
  premiumLabel: string;
  freeLabel: string;
  trialSuffix: (days: number) => string;
  pricingLine: { monthly: string; quarterly: string; yearly: string; connector1: string; connector2: string };
  buySubscriptionCta: string;
  downloadTrialCta: string;
  moreToolsLabel: string;
  galleryHeading: string;
  videoHeading: string;
  viewBimtoolsCta: string;
  downloadTrialShortCta: string;
  privacyLabel: string;
}

export const bimtoolsManualDetailContent: Record<Locale, BimtoolsManualDetailContent> = {
  es: {
    notFoundTitle: "Manual no encontrado",
    metaSuffix: "Manual BIMtools",
    backToBimtools: "Volver a BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Gratis",
    trialSuffix: (days) => ` · Prueba de ${days} días`,
    pricingLine: {
      monthly: "USD 20/mes",
      quarterly: "USD 40/trimestre",
      yearly: "USD 100/año",
      connector1: "Accede a este addin y a todos los addins premium por",
      connector2: "o",
    },
    buySubscriptionCta: "Comprar suscripción premium",
    downloadTrialCta: "Descargar instalador de prueba",
    moreToolsLabel: "Más herramientas de esta suite",
    galleryHeading: "Galería",
    videoHeading: "Video",
    viewBimtoolsCta: "Ver BIMtools",
    downloadTrialShortCta: "Descargar prueba",
    privacyLabel: "Política de privacidad de BIMtools",
  },
  en: {
    notFoundTitle: "Manual not found",
    metaSuffix: "BIMtools Manual",
    backToBimtools: "Back to BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Free",
    trialSuffix: (days) => ` · ${days}-day trial`,
    pricingLine: {
      monthly: "USD 20/month",
      quarterly: "USD 40/quarter",
      yearly: "USD 100/year",
      connector1: "Get this add-in and every premium add-in for",
      connector2: "or",
    },
    buySubscriptionCta: "Buy premium subscription",
    downloadTrialCta: "Download trial installer",
    moreToolsLabel: "More tools in this suite",
    galleryHeading: "Gallery",
    videoHeading: "Video",
    viewBimtoolsCta: "View BIMtools",
    downloadTrialShortCta: "Download trial",
    privacyLabel: "BIMtools privacy policy",
  },
  de: {
    notFoundTitle: "Handbuch nicht gefunden",
    metaSuffix: "BIMtools-Handbuch",
    backToBimtools: "Zurück zu BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Kostenlos",
    trialSuffix: (days) => ` · ${days}-Tage-Testversion`,
    pricingLine: {
      monthly: "USD 20/Monat",
      quarterly: "USD 40/Quartal",
      yearly: "USD 100/Jahr",
      connector1: "Erhalten Sie Zugang zu diesem Addin und allen Premium-Addins für",
      connector2: "oder",
    },
    buySubscriptionCta: "Premium-Abo kaufen",
    downloadTrialCta: "Test-Installer herunterladen",
    moreToolsLabel: "Weitere Werkzeuge dieser Suite",
    galleryHeading: "Galerie",
    videoHeading: "Video",
    viewBimtoolsCta: "BIMtools ansehen",
    downloadTrialShortCta: "Testversion herunterladen",
    privacyLabel: "Datenschutzerklärung von BIMtools",
  },
  fr: {
    notFoundTitle: "Manuel introuvable",
    metaSuffix: "Manuel BIMtools",
    backToBimtools: "Retour à BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Gratuit",
    trialSuffix: (days) => ` · Essai de ${days} jours`,
    pricingLine: {
      monthly: "20 USD/mois",
      quarterly: "40 USD/trimestre",
      yearly: "100 USD/an",
      connector1: "Accédez à cet addin et à tous les addins premium pour",
      connector2: "ou",
    },
    buySubscriptionCta: "Acheter l'abonnement premium",
    downloadTrialCta: "Télécharger l'installateur d'essai",
    moreToolsLabel: "Autres outils de cette suite",
    galleryHeading: "Galerie",
    videoHeading: "Vidéo",
    viewBimtoolsCta: "Voir BIMtools",
    downloadTrialShortCta: "Télécharger l'essai",
    privacyLabel: "Politique de confidentialité de BIMtools",
  },
  it: {
    notFoundTitle: "Manuale non trovato",
    metaSuffix: "Manuale BIMtools",
    backToBimtools: "Torna a BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Gratis",
    trialSuffix: (days) => ` · Prova di ${days} giorni`,
    pricingLine: {
      monthly: "USD 20/mese",
      quarterly: "USD 40/trimestre",
      yearly: "USD 100/anno",
      connector1: "Accedi a questo addin e a tutti gli addin premium per",
      connector2: "o",
    },
    buySubscriptionCta: "Acquista abbonamento premium",
    downloadTrialCta: "Scarica l'installer di prova",
    moreToolsLabel: "Altri strumenti di questa suite",
    galleryHeading: "Galleria",
    videoHeading: "Video",
    viewBimtoolsCta: "Vedi BIMtools",
    downloadTrialShortCta: "Scarica la prova",
    privacyLabel: "Informativa sulla privacy di BIMtools",
  },
  pt: {
    notFoundTitle: "Manual não encontrado",
    metaSuffix: "Manual BIMtools",
    backToBimtools: "Voltar ao BIMtools",
    premiumLabel: "Premium",
    freeLabel: "Gratuito",
    trialSuffix: (days) => ` · Teste de ${days} dias`,
    pricingLine: {
      monthly: "USD 20/mês",
      quarterly: "USD 40/trimestre",
      yearly: "USD 100/ano",
      connector1: "Acesse este addin e todos os addins premium por",
      connector2: "ou",
    },
    buySubscriptionCta: "Comprar assinatura premium",
    downloadTrialCta: "Baixar instalador de teste",
    moreToolsLabel: "Mais ferramentas desta suíte",
    galleryHeading: "Galeria",
    videoHeading: "Vídeo",
    viewBimtoolsCta: "Ver BIMtools",
    downloadTrialShortCta: "Baixar versão de teste",
    privacyLabel: "Política de privacidade do BIMtools",
  },
  ru: {
    notFoundTitle: "Руководство не найдено",
    metaSuffix: "Руководство BIMtools",
    backToBimtools: "Назад к BIMtools",
    premiumLabel: "Премиум",
    freeLabel: "Бесплатно",
    trialSuffix: (days) => ` · Пробный период ${days} дней`,
    pricingLine: {
      monthly: "20 USD/мес",
      quarterly: "40 USD/квартал",
      yearly: "100 USD/год",
      connector1: "Получите доступ к этому и всем премиум-аддинам за",
      connector2: "или",
    },
    buySubscriptionCta: "Купить премиум-подписку",
    downloadTrialCta: "Скачать пробный установщик",
    moreToolsLabel: "Другие инструменты этого набора",
    galleryHeading: "Галерея",
    videoHeading: "Видео",
    viewBimtoolsCta: "Смотреть BIMtools",
    downloadTrialShortCta: "Скачать пробную версию",
    privacyLabel: "Политика конфиденциальности BIMtools",
  },
  zh: {
    notFoundTitle: "未找到该手册",
    metaSuffix: "BIMtools 手册",
    backToBimtools: "返回 BIMtools",
    premiumLabel: "高级版",
    freeLabel: "免费",
    trialSuffix: (days) => ` · ${days} 天试用`,
    pricingLine: {
      monthly: "每月 20 美元",
      quarterly: "每季度 40 美元",
      yearly: "每年 100 美元",
      connector1: "订阅后即可使用此插件及全部高级插件，价格为",
      connector2: "或",
    },
    buySubscriptionCta: "购买高级订阅",
    downloadTrialCta: "下载试用安装程序",
    moreToolsLabel: "该套件的更多工具",
    galleryHeading: "图库",
    videoHeading: "视频",
    viewBimtoolsCta: "查看 BIMtools",
    downloadTrialShortCta: "下载试用版",
    privacyLabel: "BIMtools 隐私政策",
  },
};
